# Generated by Django 5.2.11 on 2026-02-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalFeatureDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("rsi_14", models.FloatField(blank=True, null=True)),
                ("atr_14", models.FloatField(blank=True, null=True)),
                ("volatility_14", models.FloatField(blank=True, null=True)),
                ("supertrend_value", models.FloatField(blank=True, null=True)),
                (
                    "supertrend_direction",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="+1 for uptrend, -1 for downtrend",
                        null=True,
                    ),
                ),
                ("volume_zscore_20", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_features",
                        to="market_data.stock",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stock", "trade_date"],
                        name="technical_f_stock_i_84095a_idx",
                    ),
                    models.Index(
                        fields=["trade_date"], name="technical_f_trade_d_040344_idx"
                    ),
                ],
                "unique_together": {("stock", "trade_date")},
            },
        ),
    ]
