# Generated by Django 5.2.11 on 2026-03-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technical_features", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicalfeaturedaily", name="supertrend_direction",
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="bollinger_position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="ema20_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="ema50_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="supertrend_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="volume_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
