# Generated by Django 5.2.11 on 2026-03-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "technical_features",
            "0002_remove_technicalfeaturedaily_supertrend_direction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicalfeaturedaily", name="supertrend_distance",
        ),
        migrations.RemoveField(
            model_name="technicalfeaturedaily", name="supertrend_value",
        ),
    ]
