# Generated by Django 5.2.11 on 2026-03-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "technical_features",
            "0003_remove_technicalfeaturedaily_supertrend_distance_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicalfeaturedaily", name="ema20_distance",
        ),
        migrations.RemoveField(
            model_name="technicalfeaturedaily", name="volume_ratio",
        ),
        migrations.RemoveField(
            model_name="technicalfeaturedaily", name="volume_zscore_20",
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="range_10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="return_10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="return_5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="rsi_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="trend_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="technicalfeaturedaily",
            name="volatility_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
