# Generated by Django 5.2.11 on 2026-02-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("sector", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OHLCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.BigIntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlcv",
                        to="market_data.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["trade_date"],
                "indexes": [
                    models.Index(
                        fields=["stock", "trade_date"],
                        name="market_data_stock_i_94a8f2_idx",
                    )
                ],
                "unique_together": {("stock", "trade_date")},
            },
        ),
    ]
