NIFTY_50_SYMBOLS = [
"RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","ITC.NS","LT.NS","AXISBANK.NS","KOTAKBANK.NS",
"HINDUNILVR.NS","BHARTIARTL.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS","ULTRACEMCO.NS","NESTLEIND.NS","BAJFINANCE.NS",
"HCLTECH.NS","POWERGRID.NS","TITAN.NS","NTPC.NS","TATASTEEL.NS","JSWSTEEL.NS","ONGC.NS","COALINDIA.NS","TECHM.NS",
"WIPRO.NS","BAJAJFINSV.NS","ADANIENT.NS","ADANIPORTS.NS","DIVISLAB.NS","DRREDDY.NS","CIPLA.NS","HEROMOTOCO.NS",
"EICHERMOT.NS","BRITANNIA.NS","INDUSINDBK.NS","APOLLOHOSP.NS","HDFCLIFE.NS","SBILIFE.NS","UPL.NS","GRASIM.NS",
"TATACONSUM.NS","BAJAJ-AUTO.NS","SHREECEM.NS","HINDALCO.NS","M&M.NS","BPCL.NS","IOC.NS"
]
